INSERT INTO tb_categorias (nome) VALUES ('Chocolate');
INSERT INTO tb_categorias (nome) VALUES ('Embalagem');

INSERT INTO tb_material  (descricao, nome, preco, peso, quantidade, categoria_id) VALUES ('Chocolate paras os Ovos de Pascoa', 'Chocolate Branco', 10.99, 100.99, 20, 1);
INSERT INTO tb_material  (descricao, nome, preco, peso, quantidade, categoria_id) VALUES ('Chocolate paras os Ovos de Pascoa', 'Chocolate Preto', 8.99, 100.99, 35, 1);
INSERT INTO tb_material  (descricao, nome, preco, peso, quantidade, categoria_id) VALUES ('Papel de embalagem', 'Papel de embrulho', 200.00, 0.00, 50, 2);
INSERT INTO tb_material  (descricao, nome, preco, peso, quantidade, categoria_id) VALUES ('Fita para embrulho', 'Fita', 79.90, 0.00, 250, 2);


--- clientes ---
--- não insere datas de nascimento e de cadastro
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ( 'Sarah Evelyn Silva', '23234054703', 'sara_es', null, null);
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ( 'Rebeca Jaqueline Melo', '64362804307', 'rebecamelo', 'rebecamelo', null );
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ( 'Pietra Rita Assis', '22860007946', 'PitAssis_', null, 'pietraritaassis__pietraritaassis@unimedsjc.com.br' );
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ( 'Valentina Esther Fernandes', '25527765311', null, 'thether', 'valentinaestherfernandes_@raffinimobiliario.com.br' );
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ( 'Ricardo Bernardo da Silva', '61955426872', null, 'Ricnardo', 'ricardobernardodasilva_@sfreitasadvogados.com.br' );
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Martin Carlos Jorge da Luz', '25937691490', 'Martin_insta', 'face_Martin', 'mmartincarlosjorgedaluz@zepto.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Julia Benedita Heloisa da Paz', '82285135424', 'Julia_insta', 'face_Julia', 'juliabeneditaheloisadapaz-93@munhozengenharia.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Heloisa Priscila Evelyn Jesus', '45178076494', 'Heloisa_insta', 'face_Heloisa', 'heloisapriscilaevelynjesus_@djapan.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Isadora Olivia Eloá da Paz', '58982011498', 'Isadora_insta', 'face_Isadora', 'isadoraoliviaeloadapaz__isadoraoliviaeloadapaz@andrepires.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Jéssica Flávia Sebastiana Pereira', '67685171473', 'Jéssica_insta', 'face_Jéssica', 'jessicaflaviasebastianapereira-93@lubeka.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Liz Isabelly Nina Drumond', '39769806412', 'Liz_insta', 'face_Liz', 'lizisabellyninadrumond-85@luxafit.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Diego Fábio Nogueira', '09295331435', 'Diego_insta', 'face_Diego', 'ddiegofabionogueira@nogueiramoura.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Débora Elza Silveira', '90492429448', 'Débora_insta', 'face_Débora', 'deboraelzasilveira__deboraelzasilveira@shimu.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Isaac Paulo Campos', '69720677406', 'Isaac_insta', 'face_Isaac', 'isaacpaulocampos_@dkcarmo.com');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Mariane Rayssa da Paz', '13050833424', 'Mariane_insta', 'face_Mariane', 'marianerayssadapaz..marianerayssadapaz@bol.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Maitê Natália Santos', '42784595480', 'Maitê_insta', 'face_Maitê', 'maitenataliasantos__maitenataliasantos@novotempo.org.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Iago Nathan Silveira', '12462224424', 'Iago_insta', 'face_Iago', 'iagonathansilveira-73@riguetti.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Caio Bento Dias', '29747668467', 'Caio_insta', 'face_Caio', 'caiobentodias-90@ntiequipamentos.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Emanuel Otávio Diego Brito', '98917618430', 'Emanuel_insta', 'face_Emanuel', 'emanuelotaviodiegobrito__emanuelotaviodiegobrito@igui.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Diogo Henrique Gustavo Ferreira', '92298323402', 'Diogo_insta', 'face_Diogo', 'diogohenriquegustavoferreira..diogohenriquegustavoferreira@verdana.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Gabriela Marli Sabrina Baptista', '83933609437', 'Gabriela_insta', 'face_Gabriela', 'gabrielamarlisabrinabaptista..gabrielamarlisabrinabaptista@predialnet.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Mário Renan Caldeira', '25398746499', 'Mário_insta', 'face_Mário', 'mariorenancaldeira_@pobox.com');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Breno Severino Peixoto', '63252195461', 'Breno_insta', 'face_Breno', 'brenoseverinopeixoto..brenoseverinopeixoto@redealumni.com');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Melissa Olivia Nicole Novaes', '41121414400', 'Melissa_insta', 'face_Melissa', 'melissaolivianicolenovaes_@granvale.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Augusto Caleb Pereira', '31369056443', 'Augusto_insta', 'face_Augusto', 'augustocalebpereira_@amaralmonteiro.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Daniel Bernardo Ryan da Paz', '52784836444', 'Daniel_insta', 'face_Daniel', 'danielbernardoryandapaz..danielbernardoryandapaz@giltelhas.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Sueli Sarah Elaine Rocha', '37887177421', 'Sueli_insta', 'face_Sueli', 'suelisarahelainerocha..suelisarahelainerocha@moen.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Isabel Elza Tatiane da Conceição', '53589791403', 'Isabel_insta', 'face_Isabel', 'isabelelzatatianedaconceicao..isabelelzatatianedaconceicao@vmetaiscba.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Sebastiana Antonella Nascimento', '28101878432', 'Sebastiana_insta', 'face_Sebastiana', 'sebastianaantonellanascimento..sebastianaantonellanascimento@mirafactoring.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Brenda Isabelly Aparício', '00487225457', 'Brenda_insta', 'face_Brenda', 'brendaisabellyaparicio_@maptec.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Patrícia Bruna Mariane Carvalho', '64331873404', 'Patrícia_insta', 'face_Patrícia', 'patriciabrunamarianecarvalho..patriciabrunamarianecarvalho@origembr.com');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Kauê Benício Renan Drumond', '61339772485', 'Kauê_insta', 'face_Kauê', 'kkauebeniciorenandrumond@estadao.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Olivia Lara Farias', '62577116497', 'Olivia_insta', 'face_Olivia', 'olivialarafarias..olivialarafarias@unitau.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Jorge Vicente Nogueira', '03619838402', 'Jorge_insta', 'face_Jorge', 'jorgevicentenogueira..jorgevicentenogueira@universo3d.com.br');
INSERT INTO tb_cliente (nome, cpf, instagram, facebook, email) VALUES ('Davi Nelson Baptista', '83757350430', 'Davi_insta', 'face_Davi', 'davinelsonbaptista_@djapan.com.br');


--- telefones ---
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '32356050', false, 'trabalho fds',   '1');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '991152198', true, null,             '1');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '996185740', true, null, 			'2');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '990690637', false, null, 			'3');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '32354900', false, null, 			'4');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '35122009', false, 'Ramal trabalho', '5');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '997916971', true, null, 			'6');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (27, '28119059', false, null, 			'7');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '996502840', false, 'tim', 			'8');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '992339989', true, 'tim', 			'9');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '985231280', true, 'tim',   			'10');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '982917496', true, 'vivo',           '11');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '991230036', true, 'vivo',           '12');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '994960355', true, 'vivo',           '13');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '981010372', true, 'vivo',           '14');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '995519562', true, 'vivo',           '15');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '986367720', true, 'vivo',           '16');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '985327101', false, 'vivo',          '17');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '996240862', false, 'vivo',          '18');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '983017911', false, 'vivo',          '19');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '986187013', false, 'vivo',          '20');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '987050250', false, 'vivo',          '21');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '994596762', false, 'vivo',          '22');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '993624470', false, 'vivo',          '23');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '988888332', true, 'vivo',           '25');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '992802826', true, 'vivo',           '26');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '983276876', true, 'tim',            '27');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '992320525', true, 'tim',            '28');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '993492908', true, null,             '29');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '982361027', true, null,             '30');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '996726672', true, null,             '31');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '993877488', true, null,             '32');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '989774426', true, null,             '33');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '994684422', true, null,             '34');
INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '999056482', false, null,            '35');
--INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '991152198', false, null,            '36');
--INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '997746938', false, null,            '37');
--INSERT INTO tb_telefone (ddd, numero, whatsapp, observacao, id_cliente_fk) VALUES (83, '984962176', false, null,            '38');

--- enderecos ---
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ('Rua Estudante Júlio Cezar Soares da Silva', '287', 'Valentina de Figueiredo', null,	 '1'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Mestre Júlio Sarmento', '768', 'Bancários', null, 								 '1');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Severino Neves de Lima', '185', 'Mangabeira', null,								 '1');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ('Rua Severina de Freitas', '362', 'Mandacaru', null,									 '2'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ('Rua Francisco Guimarães', '650', 'Ipês', null,										 '3'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ('Rua Aluísio Bezerra da Silva', '207', 'Portal do Sol', null,							 '4'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ('Rua Valdemiro Ferreira da Silva', '819', 'Nações', null,								 '5'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ('Rua Professor Oswaldo de Miranda Pereira', '623', 'Brisamar', null, 					 '6'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ('Rua Aparecida', '690', 'Nova Conquista', null,										 '7'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ('Rua Maria Eulina', '110', 'Popular', null, 											 '8'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Turquia', '193', 'Indústrias', null, 										     '9'); 
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Peregrino de Carvalho', '717', 'Centro', null,									 '10');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Lins de Vasconcelos', '747', 'Treze de Maio', null,								 '11');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Travessa Patrícia Vieira', '306', 'Santo Antônio', null,							 '12');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua João Pereira de Arruda', '175', 'Funcionários', null,							 '13');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Praça Noé Rodrigues de Lima, s\/n', '704', 'Centro', null,							 '14');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua José Fernandes de Lima', '910', 'Comercial Norte', null,						 '15');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua B', '243', 'Distrito Industrial', null, 										 '16');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Doutor Aroldo Cruz', '651', 'Itararé', null,									 '17');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Luzia Ferreira Leitão', '166', 'Jatobá', null, 									 '18');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Gilberto Stuckert', '296', 'Jardim Oceania', null,								 '19');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Mar da Galiléia', '705', 'Gramame', null,										 '20');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Jamaica', '986', 'Serrotão', null, 												 '21');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Romildo Domingues de Melo', '990', 'Gramame', null,								 '22');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Levi Benedito', '729', 'Treze de Maio', null, 									 '23');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Doutor Carlos Pires de Sá', '733', 'Areias', null,								 '25');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Belarmino da Silva Amorim', '406', 'Liberdade', null,							 '26');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua José Ciciliano de Souza Barbosa', '743', 'Mangabeira', null,					 '27');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Basta Gomes', '260', 'Santo Antônio', null, 									 '28');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Antônio Jerônimo', '350', 'Rio do Meio', null,									 '29');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Loteamento Barra de Ouro', '151', 'Indústrias', null, 								 '30');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Maria Hosana Lelis', '514', 'Três Irmãs', null,									 '31');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Praça Doutor João Úrsulo 17', '780', 'Centro', null,								 '32');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua da Abolição', '837', 'Treze de Maio', null, 									 '33');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Sebastião Lucena de Castro', '613', 'Jardim Paulistano', null,                   '34');
INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Maria José Gomes do Amaral', '421', 'Alto do Mateus', null, 				     '35');
--INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Mestre Júlio Sarmento', '768', 'Bancários', null, 								 '36');
--INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Severino Neves de Lima', '185', 'Mangabeira', null,								 '37');
--INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua Evaldo Wanderley', '114', 'Tambauzinho', null, 									 '38');
--INSERT INTO tb_endereco (rua, numero, bairro, complemento, id_cliente_fk) VALUES ( 'Rua José Gaspar', '641', 'Alto da Tubiba', null, 									 '39');
